runtime: go112

env_variables: 
  GO111MODULE: on

# TODO(zooraze): Figure out why app no longer deploys
# Relative filepath to the directory containing main package.
# main: ./server 

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
  - url: /web/dist
    static_dir: dist

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto